version: '3'

volumes:
  rabbitmq:

services:
  rabbit:
    hostname: 'rabbit'
    image: rabbitmq:3.9.22-management-alpine
    ports:
      - "5672:5672"
      - "15691:15691"
      - "15692:15692"
      - "25672:25672"
      - "15671:15671"
      - "15672:15672"
    volumes:
      - "rabbitmq:/var/lib/rabbitmq"
